spring.application.name=TecerTaller
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/blog_db
spring.datasource.username=${DATABES_USER_NAME}
spring.datasource.password=${DATABES_USER_PASWORD}
server.port=8080
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jackson.serialization.fail-on-empty-beans=false
logging.level.org.hibernate=ERROR
